### ISSUE TITLE
Feature request: scan and remove tool

### ISSUE THREAD

**Issue by hooby3dfx** [jgamblin/Mirai-Source-Code#12]
I know this may not be the best place for this request, please let me know if there is work already in progress somewhere on this.

Phase 1 of program would be something that scans the devices on your LAN (scan could be based on tool like fing) and probes them for signs of mirai, which could at least alert people to disconnect those devices.

Phase 2 could delete mirai and prevent it from coming back.

**Comment by Elycin** [comment]
This is somewhat impossible due to the design of the botnet, and the fact that there is no firmware update for the vulnerable devices; Please allow me to explain:

1. The application once on the device is executed, then deleted with the running copy still in memory
2. right in the main method, it will stop the telnet and HTTP webserver, and then bind to those ports to prevent anyone else from getting in.
3. Since the malware deletes its footprint once running, a reboot would be the only way to remove it.
4. Once rebooted, you only have a few more minutes before another scanner out of the botnet finds the device again.
