### ISSUE TITLE
setup environment

### ISSUE THREAD

**Issue by 1493553306** [jgamblin/Mirai-Source-Code#31]
Thank you for your share. I have a problem when I setup environment.

when I Compiles to ./mirai/debug like ./build.sh debug telnet. it shows 
cnc/database.go:8:5: cannot find package "github.com/go-sql-driver/mysql" in any of:
/usr/lib/go/src/pkg/github.com/go-sql-driver/mysql (from $GOROOT)
/home/xu/Documents/go/src/github.com/go-sql-driver/mysql (from $GOPATH)
cnc/attack.go:10:5: cannot find package "github.com/mattn/go-shellwords" in any of:
/usr/lib/go/src/pkg/github.com/mattn/go-shellwords (from $GOROOT)
/home/xu/Documents/go/src/github.com/mattn/go-shellwords (from $GOPATH)

then I copy the script in cnc to the folder it points out . 
it shows 
package github.com/go-sql-driver/mysql
imports github.com/mattn/go-shellwords
imports github.com/mattn/go-shellwords

how should I disturbe the script from the ./mirai/cnc?

I appreciate it if you can help me.

**Comment by osDanielLee** [comment]
I have this problem too
            On 11/08/2016 22:56, 1493553306 wrote:Thank you for your share. I have a problem when I setup environment.
when I Compiles to ./mirai/debug like ./build.sh debug telnet. it shows
cnc/database.go:8:5: cannot find package "github.com/go-sql-driver/mysql" in any of:
/usr/lib/go/src/pkg/github.com/go-sql-driver/mysql (from $GOROOT)
/home/xu/Documents/go/src/github.com/go-sql-driver/mysql (from $GOPATH)
cnc/attack.go:10:5: cannot find package "github.com/mattn/go-shellwords" in any of:
/usr/lib/go/src/pkg/github.com/mattn/go-shellwords (from $GOROOT)
/home/xu/Documents/go/src/github.com/mattn/go-shellwords (from $GOPATH)
then I copy the script in cnc to the folder it points out .
it shows
package github.com/go-sql-driver/mysql
imports github.com/mattn/go-shellwords
imports github.com/mattn/go-shellwords
how should I disturbe the script from the ./mirai/cnc?
I appreciate it if you can help me.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jgamblin/Mirai-Source-Code","title":"jgamblin/Mirai-Source-Code","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jgamblin/Mirai-Source-Code"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"setup environment (#31)"}],"action":{"name":"View Issue","url":"https://github.com/jgamblin/Mirai-Source-Code/issues/31"}}}

**Comment by samrocketman** [comment]
This is not a help forum for how to build and get Mirai running.

**Comment by 1493553306** [comment]
I found i asked a stupid question, I have soved it. Anyway, thanks.

**Comment by samrocketman** [comment]
I wouldn't call it stupid.  Just out of scope for the intent of this probject which exists for studying.

**Comment by chuckixia** [comment]
if you're interested, i forked this and made a build environment for mirai
https://github.com/chuckixia/Mirai-Source-Code

**Comment by 1493553306** [comment]
Thanks a lot, it will be helpful.

**Comment by 1493553306** [comment]
I’m a little confused about the：case UPLOAD_TFTP in /loader/src/service.c. it's in order to up load dlr.mpsl or mirai.mpsl? I think is dlr.mpsl, but the parameter 'mirai' really makes me confused.

**Comment by hasufell** [comment]
> if you're interested, i forked this and made a build environment for mirai

Mind that, in some countries, that could already be interpreted as a criminal offence.

**Comment by Bashta** [comment]
@hasufell can you link please. could not find in your repos.
